name: BowsArrow
version: 1.0-SNAPSHOT
main: me.ghalidouga.bowsarrow.BowsArrow
api-version: 1.13
authors: [ghalidouga]
description: Mini game 5Bows1Arrow
commands:
  ready:
    description:  Untuk berganti mode bersiap.
    usage: /<command>

  unready:
    description:  Untuk membatalkan ready.
    usage: /<command>